### ISSUE TITLE
Switch to svg-to-vue-component

### ISSUE THREAD

**Issue by manniL** [Developmint/nuxt-svg-loader#19]
Currently considering to switch https://github.com/egoist/svg-to-vue-component instead of `vue-svg-loader` as the former supports hot-reload 🤔 

- [x] SVGO options (https://github.com/egoist/svg-to-vue-component/issues/2)

**Comment by patrickcate** [comment]
> The latter only supports class and style attributes on the generated component while we support all DOM props and events.

This is a huge plus of [svg-to-vue-component](https://github.com/egoist/svg-to-vue-component) as well

**Comment by manniL** [comment]
@patrickcate Agreed!
