### ISSUE TITLE
not work ESLint on save

### ISSUE THREAD

**Issue by uto-usui** [Developmint/nuxt-svg-loader#39]
HI, thanks to great work.

https://github.com/Developmint/nuxt-svg-loader#how-to-fix-eslint-auto-lint-error

When I wrote this code to avoid lint error from nuxt-svg-loader, eslint for vue and js files was disabled in all cases.
I created a project with create-nuxt-app.

Could anyone help me?
Thanks.

**Comment by Anaphase** [comment]
Yeah, the regex in the README isn't doing what it's supposed to do... I'm pretty sure it should be:

```javascript
/(node_modules)|(\.svg$)/
```

**Comment by uto-usui** [comment]
@Anaphase 

It work !
Thank you for your help 🙏🏻
