### ISSUE TITLE
Are there benefits in using this module over "svg-to-vue-component" for static apps?

### ISSUE THREAD

**Issue by mornir** [Developmint/nuxt-svg-loader#59]
Hi! Thanks for this module!

I build static websites (with `nuxt generate`) and I was wondering about the benefits in using this module over just using `svg-to-vue-component`.

**Comment by manniL** [comment]
Hey 👋🏻

This module will do the Nuxt configuration work so you don't have to wire svg-to-vue-component up on your own.
